import type { NextPage } from 'next';
import Head from 'next/head';
import { SSRProps } from '@ts-types/custom.types';
import type { GetServerSideProps } from 'next';
import XSRFHandler from '@lib/csrf';
import StaffForm from '@components/staff/staff-form';

const Home: NextPage = ({ csrfToken, csrfError }: SSRProps) => {
  // Log csrfError if any
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center m-5 font-semibold">
        Server-side CSRF Protection Using Nextjs and Expressjs
      </h1>
      <main className="w-full">
        <div className="flex justify-center">
          <StaffForm csrfToken={csrfToken} />
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  // Do your JWT validation here

  const { csrfToken, csrfError } = await XSRFHandler(context);

  return {
    props: {
      csrfToken,
      csrfError
    }
  };
};

export default Home;
