import type { NextPage } from 'next';
import Head from 'next/head';
import { SSRProps } from '@ts-types/custom.types';
import type { GetServerSideProps } from 'next';
import XSRFHandler from '@lib/csrf'
import StaffForm from '@components/StaffForm'

const Home: NextPage = ({csrfToken, csrfError}:SSRProps) => {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>

        <StaffForm csrfToken={csrfToken}/>
        
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  // Do JWT validation here

  const { csrfToken, csrfError } = await XSRFHandler(context);

  return {
    props: {
      csrfToken,
      csrfError
    }
  };
};

export default Home;
